# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

# Site settings
title: MR NOOBIE
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there. Nothing awesome here. Just an experimental newbie website 
  used for testing. More contents will be uploaded here in the near future. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://misternoobie.com" # the base hostname & protocol for your site
twitter_username: none
github_username:  misternoobie
psn_username: misternoobie
steam_username: misternoobie1
battlenet_username: misternoobie1466
youtube_username: https://www.youtube.com/user/reinventyourexit01
# Build settings
markdown: kramdown
